import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,readFile} from 'node:fs/promises';import {load} from './extension-loader.mjs';import {githubFixture} from './github-fixture.mjs';
const module=await load('../src/operations.ts').catch(()=>({}));
test('generic GitHub service exists',()=>assert.equal(typeof module.runGithubOperation,'function'));
const run=(...args)=>module.runGithubOperation(...args);
for(const name of ['gh_issue_get','gh_issue_list','gh_subissues_list','gh_dependencies_list'])test(name+' returns bounded GitHub data',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),r=await run(name,{repo:'example/demo',...(name==='gh_issue_list'?{}:{issue:10})},f.context);assert.equal(r.status,'read',JSON.stringify(r));const calls=await f.calls();assert.ok(calls.every(c=>c.args.includes('github.com')));});
for(const [name,change,method,endpoint,body] of [
 ['gh_issue_edit',{operation:'issue-edit',issue:10,title:'Updated',body:'New body'},'PATCH','repos/example/demo/issues/10',{title:'Updated',body:'New body'}],
 ['gh_issue_close',{operation:'issue-close',issue:10},'PATCH','repos/example/demo/issues/10',{state:'closed',state_reason:'completed'}],
 ['gh_subissue_add',{operation:'subissue-add',issue:10,relatedIssue:11},'POST','repos/example/demo/issues/10/sub_issues',{sub_issue_id:1011}],
 ['gh_dependency_add',{operation:'dependency-add',issue:10,relatedIssue:11},'POST','repos/example/demo/issues/10/dependencies/blocked_by',{issue_id:1011}]
])test(name+' resolves IDs and applies exact request',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),args=await f.draft(change),r=await run(name,args,f.context);assert.equal(r.status,'applied',JSON.stringify(r));const writes=(await f.calls()).filter(c=>c.method!=='GET');assert.equal(writes.length,1);assert.equal(writes[0].method,method);assert.equal(writes[0].endpoint,endpoint);assert.deepEqual(writes[0].body,body);});
for(const mode of ['pr','drift','error'])test('issue edit rejects '+mode+' without writing',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await f.mode(mode);const r=await run('gh_issue_edit',await f.draft({operation:'issue-edit',issue:10,title:'Updated'}),f.context);assert.equal(r.status,'rejected',JSON.stringify(r));assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,0);});
test('noninteractive absence, permission mismatch/staleness, secret and unknown args fail closed',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),args=await f.draft({operation:'issue-edit',issue:10,title:'Updated'});f.context.interactive=false;assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');assert.equal((await f.calls()).length,0);f.context.permissions={allows:()=>false,isCurrent:async()=>true};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');f.context.permissions={allows:()=>true,isCurrent:async()=>false};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');f.context.permissions={allows:()=>true,isCurrent:async()=>true};assert.equal((await run('gh_issue_edit',{...args,approved:true},f.context)).status,'rejected');const secret=await f.draft({operation:'issue-edit',issue:10,body:'password="synthetic-secret-value"'});const r=await run('gh_issue_edit',secret,f.context);assert.equal(r.status,'rejected');assert.ok(!JSON.stringify(r).includes('synthetic-secret-value'));});
test('exact machine permission permits headless write without UI',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);f.context.interactive=false;f.context.confirm=async()=>{throw new Error('UI forbidden');};f.context.permissions={allows:(op,repo)=>op==='gh_issue_close'&&repo==='example/demo',isCurrent:async()=>true};assert.equal((await run('gh_issue_close',await f.draft({operation:'issue-close',issue:10}),f.context)).status,'applied');});
test('mutation uncertainty is unknown with no retry',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await f.mode('write-error');const r=await run('gh_issue_edit',await f.draft({operation:'issue-edit',issue:10,title:'Updated'}),f.context);assert.equal(r.status,'unknown');assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,1);});
test('input drift and session cancellation after approval deny mutation',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),args=await f.draft({operation:'issue-edit',issue:10,title:'Updated'});f.context.confirm=async()=>{await writeFile(args.changePath,(await readFile(args.changePath,'utf8'))+' ');return true;};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,0);f.context.confirm=async()=>{f.context.isCurrent=()=>false;return true;};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');});
for(const name of ['gh_project_get','gh_project_items'])test(name+' reads Projects V2',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);const r=await run(name,{projectId:'PVT_demo'},f.context);assert.equal(r.status,'read',JSON.stringify(r));});
test('project add uses issue node ID and verifies project membership',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),r=await run('gh_project_add_issue',await f.draft({operation:'project-add-issue',projectId:'PVT_demo',issue:10}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));const mutation=(await f.calls()).find(c=>c.body.query?.includes('mutation'));assert.equal(mutation.body.variables.contentId,'I_10');assert.equal(mutation.body.variables.projectId,'PVT_demo');});
for(const [fieldId,value] of [['PVTF_text',{text:'Hello'}],['PVTF_number',{number:3}],['PVTF_date',{date:'2026-10-07'}],['PVTSSF_status',{singleSelectOptionId:'option_done'}]])test('project field update verifies '+fieldId,async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);const data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',id:'I_10',number:10,repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[]}}];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId,value}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
for(const mode of ['graphql-error','foreign','pages'])test('project update rejects '+mode,async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),data=await f.data();data.mode=mode;data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:mode==='foreign'?'other/repo':'example/demo'}},fieldValues:{nodes:[]}}];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTSSF_status',value:{singleSelectOptionId:'option_done'}}),f.context);assert.equal(r.status,'rejected',JSON.stringify(r));assert.equal((await f.calls()).filter(c=>c.body.query?.includes('mutation')).length,0);});
test('invalid inputs self links field mismatch and invalid date are refused',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);for(const [name,change] of [['gh_subissue_add',{operation:'subissue-add',issue:10,relatedIssue:10}],['gh_dependency_add',{operation:'dependency-add',issue:10,relatedIssue:11,approved:true}],['gh_project_field_update',{operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_date',value:{date:'2026-02-30'}}]])assert.equal((await run(name,await f.draft(change),f.context)).status,'rejected');});
test('unrelated unsupported project field values do not block a supported field',async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[{__typename:'ProjectV2ItemFieldLabelValue'}]}}];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_text',value:{text:'Hello'}}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
for(const scenario of ['unrelated-secret','unrelated-drift'])test('project addition ignores '+scenario,async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_unrelated',content:{__typename:'Issue',id:'I_other',repository:{nameWithOwner:'other/repo'}},fieldValues:{nodes:[{field:{id:'PVTF_text'},text:scenario==='unrelated-secret'?'password="synthetic-unrelated-value"':'Original'}]}}];await writeFile(f.state,JSON.stringify(data));if(scenario==='unrelated-drift')f.context.confirm=async()=>{const changed=await f.data();changed.items[0].fieldValues.nodes[0].text='Unrelated update';await writeFile(f.state,JSON.stringify(changed));return true;};const r=await run('gh_project_add_issue',await f.draft({operation:'project-add-issue',projectId:'PVT_demo',issue:10}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
test('target Project field drift still rejects the write',async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[{field:{id:'PVTF_text'},text:'Original'}]}}];await writeFile(f.state,JSON.stringify(data));f.context.confirm=async()=>{const changed=await f.data();changed.items[0].fieldValues.nodes[0].text='Concurrent edit';await writeFile(f.state,JSON.stringify(changed));return true;};const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_text',value:{text:'Desired'}}),f.context);assert.equal(r.status,'rejected');assert.equal(r.problems[0].code,'APPROVAL_MISMATCH');assert.equal((await f.calls()).filter(c=>c.body.query?.includes('mutation')).length,0);});
test('Project field update ignores other fields but denies missing option and wrong type',async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[{field:{id:'PVTF_other'},text:'password="synthetic-unrelated-value"'}]}}];await writeFile(f.state,JSON.stringify(data));for(const [fieldId,value] of [['PVTSSF_status',{singleSelectOptionId:'missing'}],['PVTF_text',{number:1}],['PVTF_missing',{text:'Hello'}]]){const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId,value}),f.context);assert.equal(r.status,'rejected');}const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_text',value:{text:'Hello'}}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
