import test from 'node:test';import assert from 'node:assert/strict';import {writeFile,readFile} from 'node:fs/promises';import {load} from './extension-loader.mjs';import {githubFixture} from './github-fixture.mjs';
const module=await load('../src/operations.ts').catch(()=>({}));
test('generic GitHub service exists',()=>assert.equal(typeof module.runGithubOperation,'function'));
const run=(...args)=>module.runGithubOperation(...args);
for(const name of ['gh_issue_get','gh_issue_list','gh_subissues_list','gh_dependencies_list'])test(name+' returns bounded GitHub data',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),r=await run(name,{repo:'example/demo',...(name==='gh_issue_list'?{}:{issue:10})},f.context);assert.equal(r.status,'read',JSON.stringify(r));const calls=await f.calls();assert.ok(calls.every(c=>c.args.includes('github.com')));});
for(const [name,change,method,endpoint,body] of [
 ['gh_issue_edit',{operation:'issue-edit',issue:10,title:'Updated',body:'New body'},'PATCH','repos/example/demo/issues/10',{title:'Updated',body:'New body'}],
 ['gh_issue_close',{operation:'issue-close',issue:10},'PATCH','repos/example/demo/issues/10',{state:'closed',state_reason:'completed'}],
 ['gh_subissue_add',{operation:'subissue-add',issue:10,relatedIssue:11},'POST','repos/example/demo/issues/10/sub_issues',{sub_issue_id:1011}],
 ['gh_dependency_add',{operation:'dependency-add',issue:10,relatedIssue:11},'POST','repos/example/demo/issues/10/dependencies/blocked_by',{issue_id:1011}]
])test(name+' resolves IDs and applies exact request',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),args=await f.draft(change),r=await run(name,args,f.context);assert.equal(r.status,'applied',JSON.stringify(r));const writes=(await f.calls()).filter(c=>c.method!=='GET');assert.equal(writes.length,1);assert.equal(writes[0].method,method);assert.equal(writes[0].endpoint,endpoint);assert.deepEqual(writes[0].body,body);});
for(const mode of ['pr','drift','error'])test('issue edit rejects '+mode+' without writing',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await f.mode(mode);const r=await run('gh_issue_edit',await f.draft({operation:'issue-edit',issue:10,title:'Updated'}),f.context);assert.equal(r.status,'rejected',JSON.stringify(r));assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,0);});
test('noninteractive absence, permission mismatch/staleness, secret and unknown args fail closed',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),args=await f.draft({operation:'issue-edit',issue:10,title:'Updated'});f.context.interactive=false;assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');assert.equal((await f.calls()).length,0);f.context.permissions={allows:()=>false,isCurrent:async()=>true};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');f.context.permissions={allows:()=>true,isCurrent:async()=>false};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');f.context.permissions={allows:()=>true,isCurrent:async()=>true};assert.equal((await run('gh_issue_edit',{...args,approved:true},f.context)).status,'rejected');const secret=await f.draft({operation:'issue-edit',issue:10,body:'password="synthetic-secret-value"'});const r=await run('gh_issue_edit',secret,f.context);assert.equal(r.status,'rejected');assert.ok(!JSON.stringify(r).includes('synthetic-secret-value'));});
test('exact machine permission permits headless write without UI',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);f.context.interactive=false;f.context.confirm=async()=>{throw new Error('UI forbidden');};f.context.permissions={allows:(op,repo)=>op==='gh_issue_close'&&repo==='example/demo',isCurrent:async()=>true};assert.equal((await run('gh_issue_close',await f.draft({operation:'issue-close',issue:10}),f.context)).status,'applied');});
test('mutation uncertainty is unknown with no retry',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await f.mode('write-error');const r=await run('gh_issue_edit',await f.draft({operation:'issue-edit',issue:10,title:'Updated'}),f.context);assert.equal(r.status,'unknown');assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,1);});
test('input drift and session cancellation after approval deny mutation',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),args=await f.draft({operation:'issue-edit',issue:10,title:'Updated'});f.context.confirm=async()=>{await writeFile(args.changePath,(await readFile(args.changePath,'utf8'))+' ');return true;};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,0);f.context.confirm=async()=>{f.context.isCurrent=()=>false;return true;};assert.equal((await run('gh_issue_edit',args,f.context)).status,'rejected');});
for(const name of ['gh_project_get','gh_project_items'])test(name+' reads Projects V2',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);const r=await run(name,{projectId:'PVT_demo'},f.context);assert.equal(r.status,'read',JSON.stringify(r));});
test('project add uses issue node ID and verifies project membership',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),r=await run('gh_project_add_issue',await f.draft({operation:'project-add-issue',projectId:'PVT_demo',issue:10}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));const mutation=(await f.calls()).find(c=>c.body.query?.includes('mutation'));assert.equal(mutation.body.variables.contentId,'I_10');assert.equal(mutation.body.variables.projectId,'PVT_demo');});
for(const [fieldId,value] of [['PVTF_text',{text:'Hello'}],['PVTF_number',{number:3}],['PVTF_date',{date:'2026-10-07'}],['PVTSSF_status',{singleSelectOptionId:'option_done'}]])test('project field update verifies '+fieldId,async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);const data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',id:'I_10',number:10,repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[]}}];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId,value}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
for(const mode of ['graphql-error','foreign','pages'])test('project update rejects '+mode,async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),data=await f.data();data.mode=mode;data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:mode==='foreign'?'other/repo':'example/demo'}},fieldValues:{nodes:[]}}];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTSSF_status',value:{singleSelectOptionId:'option_done'}}),f.context);assert.equal(r.status,'rejected',JSON.stringify(r));assert.equal((await f.calls()).filter(c=>c.body.query?.includes('mutation')).length,0);});
test('invalid inputs self links field mismatch and invalid date are refused',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);for(const [name,change] of [['gh_subissue_add',{operation:'subissue-add',issue:10,relatedIssue:10}],['gh_dependency_add',{operation:'dependency-add',issue:10,relatedIssue:11,approved:true}],['gh_project_field_update',{operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_date',value:{date:'2026-02-30'}}]])assert.equal((await run(name,await f.draft(change),f.context)).status,'rejected');});
test('unrelated unsupported project field values do not block a supported field',async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[{__typename:'ProjectV2ItemFieldLabelValue'}]}}];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_text',value:{text:'Hello'}}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
for(const scenario of ['unrelated-secret','unrelated-drift'])test('project addition ignores '+scenario,async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_unrelated',content:{__typename:'Issue',id:'I_other',repository:{nameWithOwner:'other/repo'}},fieldValues:{nodes:[{field:{id:'PVTF_text'},text:scenario==='unrelated-secret'?'password="synthetic-unrelated-value"':'Original'}]}}];await writeFile(f.state,JSON.stringify(data));if(scenario==='unrelated-drift')f.context.confirm=async()=>{const changed=await f.data();changed.items[0].fieldValues.nodes[0].text='Unrelated update';await writeFile(f.state,JSON.stringify(changed));return true;};const r=await run('gh_project_add_issue',await f.draft({operation:'project-add-issue',projectId:'PVT_demo',issue:10}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
test('target Project field drift still rejects the write',async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[{field:{id:'PVTF_text'},text:'Original'}]}}];await writeFile(f.state,JSON.stringify(data));f.context.confirm=async()=>{const changed=await f.data();changed.items[0].fieldValues.nodes[0].text='Concurrent edit';await writeFile(f.state,JSON.stringify(changed));return true;};const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_text',value:{text:'Desired'}}),f.context);assert.equal(r.status,'rejected');assert.equal(r.problems[0].code,'APPROVAL_MISMATCH');assert.equal((await f.calls()).filter(c=>c.body.query?.includes('mutation')).length,0);});
test('Project field update ignores other fields but denies missing option and wrong type',async t=>{const f=await githubFixture(t),data=await f.data();data.items=[{id:'PVTI_demo',content:{__typename:'Issue',repository:{nameWithOwner:'example/demo'}},fieldValues:{nodes:[{field:{id:'PVTF_other'},text:'password="synthetic-unrelated-value"'}]}}];await writeFile(f.state,JSON.stringify(data));for(const [fieldId,value] of [['PVTSSF_status',{singleSelectOptionId:'missing'}],['PVTF_text',{number:1}],['PVTF_missing',{text:'Hello'}]]){const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId,value}),f.context);assert.equal(r.status,'rejected');}const r=await run('gh_project_field_update',await f.draft({operation:'project-field-update',projectId:'PVT_demo',itemId:'PVTI_demo',fieldId:'PVTF_text',value:{text:'Hello'}}),f.context);assert.equal(r.status,'applied',JSON.stringify(r));});
const label=(i,extra={})=>({id:i,node_id:'LA_'+i,name:'label '+String(i).padStart(3,'0'),color:'ABCDEF',description:i%2?null:'説明 '+i,url:'https://api.github.com/x',...extra});
test('gh_labels_list returns every label across pages, normalized and sorted',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),data=await f.data();data.labels=[...Array.from({length:150},(_,i)=>label(150-i)),label(999,{name:'Blocked',color:'b60205',description:'x'})];await writeFile(f.state,JSON.stringify(data));const r=await run('gh_labels_list',{repo:'example/demo'},f.context);assert.equal(r.status,'read',JSON.stringify(r));assert.equal(r.data.repo,'example/demo');assert.equal(r.data.labels.length,151);assert.deepEqual(r.data.labels[0],{name:'Blocked',color:'b60205',description:'x'});assert.deepEqual(r.data.labels[1],{name:'label 001',color:'abcdef',description:''});assert.deepEqual(r.data.labels[2],{name:'label 002',color:'abcdef',description:'説明 2'});assert.ok((await f.calls()).every(c=>c.method==='GET'&&c.args.includes('github.com')));});
test('gh_labels_list handles empty repositories and exact page sizes',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);assert.deepEqual((await run('gh_labels_list',{repo:'example/demo'},f.context)).data,{repo:'example/demo',labels:[]});const data=await f.data();data.labels=Array.from({length:100},(_,i)=>label(i+1));await writeFile(f.state,JSON.stringify(data));assert.equal((await run('gh_labels_list',{repo:'example/demo'},f.context)).data.labels.length,100);});
for(const [name,labels] of [['case duplicates',[label(1,{name:'Wave: 1'}),label(2,{name:'wave: 1'})]],['invalid color',[label(1,{color:'xyz'})]],['missing name',[label(1,{name:''})]]])test('gh_labels_list rejects '+name,async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t),data=await f.data();data.labels=labels;await writeFile(f.state,JSON.stringify(data));assert.equal((await run('gh_labels_list',{repo:'example/demo'},f.context)).status,'rejected');});
test('gh_labels_list fails closed on errors and unknown arguments without writing',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);assert.equal((await run('gh_labels_list',{repo:'example/demo',page:2},f.context)).status,'rejected');assert.equal((await run('gh_labels_list',{repo:'bad'},f.context)).status,'rejected');await f.mode('error');assert.equal((await run('gh_labels_list',{repo:'example/demo'},f.context)).status,'rejected');assert.equal((await f.calls()).filter(c=>c.method!=='GET').length,0);});
test('gh_issue_list filters by labels server-side (AND) and keeps paging/PR exclusion',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);const r=await run('gh_issue_list',{repo:'example/demo',labels:['Type: Scaffold','Scope: Epic']},f.context);assert.equal(r.status,'read',JSON.stringify(r));const lists=(await f.calls()).filter(c=>c.endpoint.startsWith('repos/example/demo/issues?'));assert.ok(lists.length>=1);assert.ok(lists.every(c=>c.endpoint.includes('state=all')&&c.endpoint.includes('labels='+encodeURIComponent('Type: Scaffold,Scope: Epic'))),JSON.stringify(lists.map(c=>c.endpoint)));});
test('gh_issue_list without labels is unchanged',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);assert.equal((await run('gh_issue_list',{repo:'example/demo'},f.context)).status,'read');assert.ok((await f.calls()).every(c=>!c.endpoint.includes('labels=')));});
for(const [name,labels] of [['empty',[]],['eleven',Array.from({length:11},(_,i)=>'l'+i)],['comma',['a,b']],['blank',['  ']],['duplicate',['Bug','bug']],['not array','Bug']])test('gh_issue_list rejects labels '+name+' without reading',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);assert.equal((await run('gh_issue_list',{repo:'example/demo',labels},f.context)).status,'rejected');assert.equal((await f.calls()).length,0);});
import {createHash} from 'node:crypto';
const sha=t=>createHash('sha256').update(t,'utf8').digest('hex');
const labelsSha=names=>sha(JSON.stringify([...names].sort()));
const L=(id,name)=>({id,node_id:'LA_'+id,name,color:'aaaaaa',description:''});
async function withLabels(f,issueLabels=['Type: Scaffold','Stage: Specification']){const d=await f.data();d.labels=[L(1,'Type: Scaffold'),L(2,'Stage: Specification'),L(3,'Stage: BasicDesign'),L(4,'bug')];d.issues[10].labels=issueLabels.map(n=>d.labels.find(l=>l.name===n));await writeFile(f.state,JSON.stringify(d));}
const writesOf=async f=>(await f.calls()).filter(c=>c.method!=='GET');

test('gh_issue_edit_if_current applies only when the body hash matches',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);
 const ok=await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'New body',expectedBodySha256:sha('Body')}),f.context);
 assert.equal(ok.status,'applied',JSON.stringify(ok));assert.equal((await f.data()).issues[10].body,'New body');
 const again=await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'New body',expectedBodySha256:sha('Body')}),f.context);
 assert.equal(again.status,'noop','desired state already present');
 const stale=await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'Other',expectedBodySha256:sha('Body')}),f.context);
 assert.equal(stale.status,'rejected');assert.equal(stale.problems[0].code,'PRECONDITION_FAILED');assert.equal((await writesOf(f)).length,1);});
test('gh_issue_edit_if_current rejects a body changed after approval without writing',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);
 f.context.confirm=async()=>{const d=await f.data();d.issues[10].body='Concurrent';await writeFile(f.state,JSON.stringify(d));return true;};
 const r=await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'New',expectedBodySha256:sha('Body')}),f.context);
 assert.equal(r.status,'rejected');assert.equal((await writesOf(f)).length,0);assert.equal((await f.data()).issues[10].body,'Concurrent');});
test('gh_issue_labels_if_current replaces exactly the requested labels when the label set matches',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await withLabels(f);
 const r=await run('gh_issue_labels_if_current',await f.draft({operation:'issue-labels-if-current',issue:10,add:['Stage: BasicDesign'],remove:['Stage: Specification'],expectedLabelsSha256:labelsSha(['Type: Scaffold','Stage: Specification'])}),f.context);
 assert.equal(r.status,'applied',JSON.stringify(r));assert.deepEqual((await f.data()).issues[10].labels.map(l=>l.name).sort(),['Stage: BasicDesign','Type: Scaffold']);
 const w=await writesOf(f);assert.equal(w.length,1);assert.equal(w[0].endpoint,'repos/example/demo/issues/10');assert.deepEqual(w[0].body.labels.sort(),['Stage: BasicDesign','Type: Scaffold']);
 const again=await run('gh_issue_labels_if_current',await f.draft({operation:'issue-labels-if-current',issue:10,add:['Stage: BasicDesign'],remove:['Stage: Specification'],expectedLabelsSha256:labelsSha(['Type: Scaffold','Stage: Specification'])}),f.context);
 assert.equal(again.status,'noop');});
test('gh_issue_labels_if_current stops on a stale label set or an unknown label',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await withLabels(f,['Type: Scaffold','Stage: Specification','bug']);
 const stale=await run('gh_issue_labels_if_current',await f.draft({operation:'issue-labels-if-current',issue:10,add:['Stage: BasicDesign'],remove:['Stage: Specification'],expectedLabelsSha256:labelsSha(['Type: Scaffold','Stage: Specification'])}),f.context);
 assert.equal(stale.status,'rejected');assert.equal(stale.problems[0].code,'PRECONDITION_FAILED');
 const missing=await run('gh_issue_labels_if_current',await f.draft({operation:'issue-labels-if-current',issue:10,add:['Wave: 9'],expectedLabelsSha256:labelsSha(['Type: Scaffold','Stage: Specification','bug'])}),f.context);
 assert.equal(missing.status,'rejected');assert.equal(missing.problems[0].code,'LABEL_MISSING');assert.equal((await writesOf(f)).length,0);});
test('gh_issue_close_if_current closes only the confirmed body',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);
 const stale=await run('gh_issue_close_if_current',await f.draft({operation:'issue-close-if-current',issue:10,expectedBodySha256:sha('Other')}),f.context);
 assert.equal(stale.status,'rejected');assert.equal((await writesOf(f)).length,0);
 const ok=await run('gh_issue_close_if_current',await f.draft({operation:'issue-close-if-current',issue:10,expectedBodySha256:sha('Body')}),f.context);
 assert.equal(ok.status,'applied',JSON.stringify(ok));assert.equal((await f.data()).issues[10].state,'closed');
 assert.equal((await run('gh_issue_close_if_current',await f.draft({operation:'issue-close-if-current',issue:10,expectedBodySha256:sha('Body')}),f.context)).status,'noop');});
test('conditional changes validate their inputs strictly',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);
 for(const [name,change] of [
  ['gh_issue_edit_if_current',{operation:'issue-edit-if-current',issue:10,body:'x',expectedBodySha256:'abc'}],
  ['gh_issue_edit_if_current',{operation:'issue-edit-if-current',issue:10,body:'x'}],
  ['gh_issue_edit_if_current',{operation:'issue-edit-if-current',issue:10,title:'t',body:'x',expectedBodySha256:sha('Body')}],
  ['gh_issue_labels_if_current',{operation:'issue-labels-if-current',issue:10,expectedLabelsSha256:sha('x')}],
  ['gh_issue_labels_if_current',{operation:'issue-labels-if-current',issue:10,add:['a'],remove:['A'],expectedLabelsSha256:sha('x')}],
  ['gh_issue_close_if_current',{operation:'issue-close-if-current',issue:10,expectedBodySha256:sha('Body'),reason:'duplicate'}],
  ['gh_issue_edit',{operation:'issue-edit-if-current',issue:10,body:'x',expectedBodySha256:sha('Body')}],
 ])assert.equal((await run(name,await f.draft(change),f.context)).status,'rejected',JSON.stringify(change));
 assert.equal((await writesOf(f)).length,0);});
test('conditional changes honour exact machine permissions',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);f.context.interactive=false;f.context.confirm=async()=>{throw new Error('UI forbidden');};
 f.context.permissions={allows:(op,repo)=>op==='gh_issue_edit_if_current'&&repo==='example/demo',isCurrent:async()=>true};
 assert.equal((await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'B2',expectedBodySha256:sha('Body')}),f.context)).status,'applied');
 assert.equal((await run('gh_issue_close_if_current',await f.draft({operation:'issue-close-if-current',issue:10,expectedBodySha256:sha('B2')}),f.context)).status,'rejected');});
test('emptying a body is recognized when GitHub stores it as null',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await f.mode('null-empty-body');
 const r=await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'',expectedBodySha256:sha('Body')}),f.context);
 assert.equal(r.status,'applied',JSON.stringify(r));
 const again=await run('gh_issue_edit_if_current',await f.draft({operation:'issue-edit-if-current',issue:10,body:'',expectedBodySha256:sha('Body')}),f.context);
 assert.equal(again.status,'noop');assert.equal((await writesOf(f)).length,1);
 const plain=await run('gh_issue_edit',await f.draft({operation:'issue-edit',issue:10,body:''}),f.context);assert.equal(plain.status,'noop');});
test('a label already present in another case is noop before the exact-name check',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await withLabels(f,['Type: Scaffold','bug']);
 const r=await run('gh_issue_labels_if_current',await f.draft({operation:'issue-labels-if-current',issue:10,add:['BUG'],expectedLabelsSha256:labelsSha(['Type: Scaffold','bug'])}),f.context);
 assert.equal(r.status,'noop',JSON.stringify(r));});
test('verification after a label change does not re-list repository labels',async t=>{if(!module.runGithubOperation)return;const f=await githubFixture(t);await withLabels(f);
 await run('gh_issue_labels_if_current',await f.draft({operation:'issue-labels-if-current',issue:10,add:['bug'],expectedLabelsSha256:labelsSha(['Type: Scaffold','Stage: Specification'])}),f.context);
 const calls=await f.calls(),patch=calls.findIndex(c=>c.method==='PATCH');assert.ok(patch>0);
 assert.equal(calls.slice(patch+1).filter(c=>c.endpoint.includes('/labels')).length,0);});
