import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,realpath,writeFile,chmod,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {load} from './extension-loader.mjs';
const module=await load('../src/permissions.ts').catch(()=>({}));
const grant={repo:'example/demo',operations:['gh_issue_edit'],allowChild:true,allowHeadless:true,projectIds:['PVT_demo']};
async function fixture(){const dir=await realpath(await mkdtemp(join(tmpdir(),'pi-gh-permissions-')));const path=join(dir,'permissions.json');await writeFile(path,JSON.stringify({version:1,grants:[grant]}),{mode:0o600});return {dir,path};}
test('permission loader is an explicit reusable boundary',()=>assert.equal(typeof module.loadPermissions,'function'));
test('exact repo operation child headless project grants and policy invalidation',async()=>{if(!module.loadPermissions)return;const f=await fixture(),p=await module.loadPermissions(f.path,{child:true,headless:true});assert.equal(p.allows('gh_issue_edit','example/demo'),true);assert.equal(p.allows('gh_issue_close','example/demo'),false);assert.equal(p.allows('gh_issue_edit','other/repo'),false);assert.equal(p.allows('gh_issue_edit','example/demo','PVT_other'),false);assert.equal(await p.isCurrent(),true);await writeFile(f.path,JSON.stringify({version:1,grants:[]}));assert.equal(await p.isCurrent(),false);});
test('absence yields no grant and insecure or symlink policy fails closed',async()=>{if(!module.loadPermissions)return;const f=await fixture();assert.equal(await module.loadPermissions(join(f.dir,'absent'),{child:false,headless:false}),undefined);await chmod(f.path,0o644);await assert.rejects(()=>module.loadPermissions(f.path,{child:false,headless:false}));await chmod(f.path,0o600);const link=join(f.dir,'link');await symlink(f.path,link);await assert.rejects(()=>module.loadPermissions(link,{child:false,headless:false}));const parent=join(f.dir,'parent');await symlink(f.dir,parent);await assert.rejects(()=>module.loadPermissions(join(parent,'permissions.json'),{child:false,headless:false}));});
test('wildcards unknown operations duplicate keys and unauthorized actor are denied',async()=>{if(!module.loadPermissions)return;const f=await fixture();for(const g of [{...grant,repo:'*'},{...grant,operations:['gh_labels_apply']},{...grant,allowChild:'yes'}]){await writeFile(f.path,JSON.stringify({version:1,grants:[g]}));await assert.rejects(()=>module.loadPermissions(f.path,{child:true,headless:true}));}await writeFile(f.path,'{"version":1,"version":1,"grants":[]}');await assert.rejects(()=>module.loadPermissions(f.path,{child:false,headless:false}));await writeFile(f.path,JSON.stringify({version:1,grants:[{...grant,allowChild:false}]}));const p=await module.loadPermissions(f.path,{child:true,headless:true});assert.equal(p.allows('gh_issue_edit','example/demo'),false);});
