import test from 'node:test';import assert from 'node:assert/strict';import {load} from './extension-loader.mjs';
// Isolate from the developer's real ~/.pi/agent/pi-gh-permissions.json: these tests assert the no-permission paths.
{const {mkdtemp}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');process.env.HOME=await mkdtemp(join(tmpdir(),'pi-gh-tools-home-'));}
function api(){const tools=[],handlers=new Map();return {tools,handlers,registerTool:t=>tools.push(t),on:(name,fn)=>{handlers.set(name,fn);return()=>{};}};}
const context=()=>({cwd:'/synthetic',mode:'rpc',hasUI:true,sessionManager:{getSessionId:()=> 's1',getLeafId:()=> 'l1'},ui:{custom:()=>{throw new Error('UI should not open');}}});
test('factory registers compatible tools with callable sequential changes',async()=>{const {default:extension}=await load('index.ts'),p=api();await extension(p);for(const name of ['gh_issue_form','gh_issue_preview','gh_issue_submit','gh_issue_validate','gh_labels_apply','gh_labels_preview','gh_labels_validate','gh_capabilities'])assert.ok(p.tools.some(t=>t.name===name));for(const t of p.tools){if(['gh_issue_submit','gh_labels_apply'].includes(t.name)){assert.equal(t.annotations.readOnlyHint,false);assert.equal(t.exposure,'direct');assert.equal(t.executionMode,'sequential');}assert.ok(t.outputSchema);}});
test('RPC and child contexts refuse changes before filesystem or UI access',async()=>{const {default:extension}=await load('index.ts'),p=api();extension(p);for(const name of ['gh_issue_submit','gh_labels_apply']){const t=p.tools.find(t=>t.name===name),r=await t.execute('1',name==='gh_issue_submit'?{draftPath:'/not-opened'}:{changePath:'/not-opened'},undefined,undefined,context());assert.equal(r.isError,true);assert.match(JSON.stringify(r),/APPROVAL_UI_REQUIRED/);}});
test('TUI child context cannot approve external changes',async()=>{const old=process.env.PI_SUBAGENT_CHILD;process.env.PI_SUBAGENT_CHILD='1';try{const {default:extension}=await load('index.ts'),p=api();extension(p);const ctx=context();ctx.mode='tui';const r=await p.tools.find(t=>t.name==='gh_issue_submit').execute('1',{draftPath:'/not-opened'},undefined,undefined,ctx);assert.match(JSON.stringify(r),/APPROVAL_UI_REQUIRED/);}finally{if(old===undefined)delete process.env.PI_SUBAGENT_CHILD;else process.env.PI_SUBAGENT_CHILD=old;}});
test('mutated tool arguments cannot bypass schema using approved flag',async()=>{const {default:extension}=await load('index.ts'),p=api();extension(p);const r=await p.tools.find(t=>t.name==='gh_issue_submit').execute('1',{draftPath:'/not-opened',approved:true},undefined,undefined,context());assert.equal(r.isError,true);assert.match(JSON.stringify(r),/ARGUMENT/);});
test('form tool masks secret candidates across content details and structuredContent',async t=>{const {fixture}=await import('../dist/test/helpers.js');const {readFile,writeFile}=await import('node:fs/promises');const {parse,stringify}=await import('yaml');const f=await fixture(t);const value=parse(await readFile(f.path,'utf8'));value.name=`password="syntheticvalue123": 'form'`;await writeFile(f.path,stringify(value));const {default:extension}=await load('index.ts'),p=api();extension(p);const ctx=context();ctx.cwd=f.dir;const r=await p.tools.find(t=>t.name==='gh_issue_form').execute('form',{templatePath:f.path},undefined,undefined,ctx);assert.equal(r.isError,false);for(const field of ['content','details','structuredContent']){assert.ok(!JSON.stringify(r[field]).includes('syntheticvalue123'),field);assert.match(JSON.stringify(r[field]),/REDACTED/,field);}});
